version: '2'
services:
    opsomed-app:
        image: opsomed
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://opsomed-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=opsomed
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    opsomed-mongodb:
        extends:
            file: mongodb.yml
            service: opsomed-mongodb
